--- a/.platform.app.yaml
+++ b/.platform.app.yaml
@@ -60,6 +60,14 @@ crons:
         spec: '50 23 * * *'
         cmd: if [ "$PLATFORM_BRANCH" = "main" ]; then croncape php-security-checker; fi

+    run_parser:
+        # Cleanup every night at 11.50 pm (UTC).
+        spec: '*/5 * * * *'
+        cmd: croncape symfony console run-parser
+
 workers:
     messenger:
         commands: